[package]
name = "luhn_algo_exercise"
authors = ["Your Name <your.name@email.com>"]
version = "0.1.0"
license = "Apache-2.0"
edition = "2021"

# For WASM library generation
[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.87"
